# Generated by Django 6.0.6 on 2026-06-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexedmedia',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexedmedia',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
