# Generated by Django 6.0.6 on 2026-06-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0002_indexedmedia_latitude_indexedmedia_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexedmedia",
            name="caption",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text caption used to generate the embedding",
            ),
        ),
    ]
