# Generated by Django 6.0.6 on 2026-06-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0003_indexedmedia_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexedmedia',
            name='vlm_caption',
            field=models.TextField(
                blank=True, default="",
                help_text=(
                    "Visual description generated by VLM "
                    "(prepended to caption)"
                ),
            ),
        ),
    ]
